export enum QuizQuestion {
    PUBLIC_SHARING = 'PublicSharing',
    LOCATION_CATEGORY = 'LocationCategory',
    SPECIFIC_LOCATION = 'SpecificLocation',
    AUTO_SERVICE = 'AutoService',
    TRAIN_EXIT_LOCATION = 'TrainExitLocation',
    TRAIN_ENTRY_LOCATION = 'TrainEntryLocation',
    AUTO_SERVICE_DETAILS = 'AutoServiceDetails',
    AUTO_EXIT_LOCATION = 'AutoExitLocation',
    AUTO_ENTRY_LOCATION = 'AutoEntryLocation',
    ONLINE_DETAILS = 'OnlineDetails',
    DATE_AND_TIME = 'DateAndTime',
    INCIDENT_CATEGORY = 'IncidentCategory',
    ADDITIONAL_DETAILS = 'AdditionalDetails',
    POST_QUESTIONS = 'PostQuestions',
}
